services:

    postgres:
      image: postgres
      container_name: wallet_app_db
      restart: on-failure
      env_file:
        - .env
      environment:
        - POSTGRES_USER=${DB_USER}
        - POSTGRES_PASSWORD=${DB_PASS}
        - POSTGRES_DB=${DB_NAME}
        - POSTGRES_PORT=${DB_PORT}
      volumes:
       - .postgres:/var/lib/postgres/data
  
    app:
      image: wallet_app
      container_name: wallet_app
      build:
        context: .
        dockerfile: Dockerfile
      restart: always
      env_file:
        - .env
      # environment:
      #   - DATABASE_URL=postgresql://${DB_USER}:${DB_PASS}@postgres:${DB_PORT}/${DB_NAME}
      ports:
        - "8000:8000"
      command: bash -c "uvicorn app.main:app --host 0.0.0.0 --port 8000"
      volumes:
        - .:/app
      depends_on:
        - postgres
        - dev
        - migrations
    migrations:
      image: migrations
      container_name: migrations
      build: .
      command: bash -c "alembic upgrade head"
      depends_on:
        - postgres
      # environment:
      #   - DATABASE_URL=postgresql://${DB_USER}:${DB_PASS}@postgres:${DB_PORT}/${DB_NAME}
    dev:
      image: tests
      container_name: tests
      build:
        context: .
        dockerfile: Dockerfile
      command: pytest
      depends_on:
        - postgres
  