"""fix table

Revision ID: f42bbdfab22c
Revises: 
Create Date: 2025-01-25 17:46:02.667010

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f42bbdfab22c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wallets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('balance', sa.DECIMAL(precision=20, scale=3), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('wallet_operation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('wallet_id', sa.UUID(), nullable=False),
    sa.Column('operation_type', sa.String(), nullable=False),
    sa.Column('amount', sa.DECIMAL(precision=20, scale=3), nullable=False),
    sa.Column('date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['wallet_id'], ['wallets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('wallet_operation')
    op.drop_table('wallets')
    # ### end Alembic commands ###
